### ISSUE TITLE
PDF export throws an error if preview window is the active one

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#10]
click on *preview window* and then <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> and select `Markdown: Export to file` error below occurs

```
Cannot read property 'document' of undefined
TypeError: Cannot read property 'document' of undefined
    at CommandExportCurrent.<anonymous> (C:\Users\user\.vscode\extensions\jebbs.markdown-extended-0.5.5\out\src\commands\exportCurrent.js:25:58)
    at Generator.next (<anonymous>)
    at C:\Users\user\.vscode\extensions\jebbs.markdown-extended-0.5.5\out\src\commands\exportCurrent.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\user\.vscode\extensions\jebbs.markdown-extended-0.5.5\out\src\commands\exportCurrent.js:3:12)
    at CommandExportCurrent.execute (C:\Users\user\.vscode\extensions\jebbs.markdown-extended-0.5.5\out\src\commands\exportCurrent.js:22:16)
    at CommandExportCurrent.executeCatch (C:\Users\user\.vscode\extensions\jebbs.markdown-extended-0.5.5\out\src\commands\command.js:16:27)
    at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:704)
    at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:141)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by cilerler** [comment]
I just received the update and no longer getting error.  Thank you! 

Now, the question is where it saves the file?  _(If I'm in markdown side and not preview it saves to the same directory under `out` folder,  where it saves it when I run it from preview window?)_
