### ISSUE TITLE
EXTENSION DOESN"T WORK IN VSCODE-INSIDERS

### ISSUE THREAD

**Issue by akharrou** [qjebbs/vscode-markdown-extended#140]
>- Version: 1.71.0-insider
>- Commit: dd0ed9381aa5d0d43159463ccad1f7e060021580
>- Date: 2022-08-17T05:20:48.980Z (6 days ago)
>- Electron: 19.0.12
>- Chromium: 102.0.5005.167
>- Node.js: 16.14.2
>- V8: 10.2.154.15-electron.0
>- OS: Darwin x64 21.4.0
>- Sandboxed: Yes
>- Markdown Extended v1.1.1

- Invoked command: `Markdown: Format Table`

    On this selection:

    ```markdown
    <!-- file.md -->
    a | b
    - | -
    bla | text
    ```

    Error:

    ```zsh
    Align settings count and column count mismatch!
    Error: Align settings count and column count mismatch!
        at MDTable.set aligns [as aligns] (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/table/mdTable.js:50:19)
        at Object.parseMDTAble (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/table/mdTableParse.js:25:18)
        at findTable (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/table/documentTables.js:36:32)
        at Object.tablesOf (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/table/documentTables.js:7:17)
        at CommandFormateTable.execute (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/commands/formateTable.js:11:39)
        at CommandFormateTable.executeCatch (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/commands/command.js:16:27)
        at c._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63546)
        at c.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:64250)
        at i._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13689)
        at i._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13371)
        at i._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:12141)
        at i._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10843)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:8950
        at b.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
        at g.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
        at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
        at o.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18988)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:17079
        at b.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
        at g.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
        at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
        at o.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18988)
        at MessagePortMain.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:15119)
        at MessagePortMain.emit (node:events:526:28)
        at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_process_init:5:364)
    ```

- vscode-insiders: error upon export of self-contained HTML, and jpeg: `TypeError: i.containingImages?.add is not a function`

    Invoked command: `Markdown: Export to File > Self-contained HTML`

    ```
    i.containingImages?.add is not a function
    TypeError: i.containingImages?.add is not a function
        at Object.e.renderer.rules.image (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1714821)
        at s.renderInline (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1267414)
        at s.render (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1267818)
        at S.render (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1261282)
        at renderHTML (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/shared.js:42:40)
        at Object.renderPage (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/shared.js:26:16)
        at HtmlExporter.<anonymous> (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/html.js:38:33)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/html.js:4:58)
    ```

    - Invoked command: `Markdown: Export to File > JPG Image`

    ```
    i.containingImages?.add is not a function
    TypeError: i.containingImages?.add is not a function
        at Object.e.renderer.rules.image (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1714821)
        at s.renderInline (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1267414)
        at s.render (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1267818)
        at S.render (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:1261282)
        at renderHTML (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/shared.js:42:40)
        at Object.renderPage (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/shared.js:26:16)
        at PuppeteerExporter.<anonymous> (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/puppeteer.js:61:33)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/johndoe/.vscode-insiders/extensions/jebbs.markdown-extended-1.1.1/out/src/services/exporter/puppeteer.js:4:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by MarcoBuess** [comment]
> Markdown: Export to File > Self-contained HTML

Also happening in:
```
Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

From the feel of it, it happens when the `.md` gets too long. Happens also when exporting as PDF but already on smaller `.md` sizes.

**Comment by qjebbs** [comment]
v1.1.2 should fix this
