### ISSUE TITLE
Unable to export to file

### ISSUE THREAD

**Issue by piridium** [qjebbs/vscode-markdown-extended#161]
Since 1.1.4 I am unable to export files. This is the error message I get:
```
ENOENT: no such file or directory, stat 'extension-output-jebbs.markdown-extended-#1-MDExtended'
Error: ENOENT: no such file or directory, stat 'extension-output-jebbs.markdown-extended-#1-MDExtended'
    at statSync (node:fs:1692:3)
    at node:electron/js2c/node_init:2:4795
    at Object.n.statSync (/Users/max/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:3435)
    at getFileList (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/export.js:27:48)
    at MarkdownExport (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/export.js:10:24)
    at /Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/commands/exportUri.js:20:48
    at v.d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:151992)
    at v.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:151855)
    at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:32751)
    at exportUri (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/commands/exportUri.js:17:26)
```

I already tried to set puppeteer executable to `'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'` with no luck.

```
Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /Users/max/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /Users/max/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:289:27)
    at ChromeLauncher.executablePath (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:182:25)
    at PuppeteerNode.executablePath (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:156:105)
    at PuppeteerExporter.checkPuppeteerBinary (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/puppeteer.js:81:79)
    at PuppeteerExporter.Export (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/puppeteer.js:17:19)
    at MarkdownExport (/Users/max/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/export.js:16:28)
```

I ran `npm install` inside `~/.vscode/extensions/jebbs.markdown-extended-1.1.4` which did not help either.
Rolling back to 1.1.3 everything works fine.

**Comment by qjebbs** [comment]
This is because your file to export is not saved, 1.1.3 should act the same way.

**Comment by piridium** [comment]
No, this is not the case. The file _is properly saved_ and I can export it with 1.1.3 but not with 1.1.4.
I also checked if there's any difference if I just open the file or open the containing folder as workspace. There is no difference in the behaviour.

**Comment by qjebbs** [comment]
I can't reproduce it on my side

**Comment by c4tom** [comment]
I have the same problem when I try to export to PDF 

```
could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/can/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/can/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
	at ChromeLauncher.resolveExecutablePath (/home/can/.vscode/extensions/jebbs.markdown-extended-1.1.4/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:289:27)
	at ChromeLauncher.executablePath (/home/can/.vscode/extensions/jebbs.markdown-extended-1.1.4/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:182:25)
	at PuppeteerNode.executablePath (/home/can/.vscode/extensions/jebbs.markdown-extended-1.1.4/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:156:105)
	at PuppeteerExporter.checkPuppeteerBinary (/home/can/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/puppeteer.js:81:79)
	at PuppeteerExporter.Export (/home/can/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/puppeteer.js:17:19)
	at MarkdownExport (/home/can/.vscode/extensions/jebbs.markdown-extended-1.1.4/out/src/services/exporter/export.js:16:28)

```


```
cat /etc/os-release 
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy
```

**Comment by atheerix** [comment]
I have the same problem too,
with Win 11 Pro and Mac OS

```
Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: C:\Users\arix\.cache\puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: C:\Users\arix\.cache\puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
	at ChromeLauncher.resolveExecutablePath (c:\Users\arix\.vscode\extensions\jebbs.markdown-extended-1.1.4\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:289:27)
	at ChromeLauncher.executablePath (c:\Users\arix\.vscode\extensions\jebbs.markdown-extended-1.1.4\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:182:25)
	at PuppeteerNode.executablePath (c:\Users\arix\.vscode\extensions\jebbs.markdown-extended-1.1.4\node_modules\puppeteer-core\lib\cjs\puppeteer\node\PuppeteerNode.js:156:105)
	at PuppeteerExporter.checkPuppeteerBinary (c:\Users\arix\.vscode\extensions\jebbs.markdown-extended-1.1.4\out\src\services\exporter\puppeteer.js:81:79)
	at PuppeteerExporter.Export (c:\Users\arix\.vscode\extensions\jebbs.markdown-extended-1.1.4\out\src\services\exporter\puppeteer.js:17:19)
	at MarkdownExport (c:\Users\arix\.vscode\extensions\jebbs.markdown-extended-1.1.4\out\src\services\exporter\export.js:16:28)
```

**Comment by Sweefiez** [comment]
I had the same problem with version 1.1.4, but I switched to version 1.1.3 and it works fine for me. I'm running Windows 10

**Comment by dominotec** [comment]
I had the same problem with version 1.1.4 after vsCode update to version 1.19.0, but I switched to version 1.1.3 and it works. I'm running Windows 11.

**Comment by codewizard13** [comment]
> I had the same problem with version 1.1.4 after vsCode update to version 1.19.0, but I switched to version 1.1.3 and it works. I'm running Windows 11.

Can you share the steps to downgrade plugin version?

**Comment by dominotec** [comment]
# Steps to downgrade Markdown Extended Version

- Open: vsCode
- Open: vsCode **Extension Manager** (Key: Ctrl+Shift+X)
- Search for: **Markdown Extended**
- Select: **Markdown Extended extension**
- Push the button **Manage** in the Markdown Extended extension
- Select: **Install Specific Version**
- Last: reload the extension

![Markdown_Extended_Downgrade_2024-11-07](https://github.com/user-attachments/assets/2b9f143e-e462-49c9-9e64-956de5d78629)

**Comment by piridium** [comment]
It's been 8 months and we still don't have a fix for 1.1.4.
I use this extension almost every day and find it extremely handy. Thank you for the great work!
I'm afraid that some new users will encounter the same problem, realize that it doesn't work and then remove the extension without ever getting the hint to downgrade to 1.1.3.
Can you at least give us a tip from the error messages posted as to how we can start troubleshooting?

**Comment by Manu-Caminos** [comment]
Faced the same issue, but fortunately it was quite easy to fix, at least in my case. Steps I took (Windows 11):

- Fresh installation of puppeteer (npm i puppeteer)
- Puppeteer will install itself on something like c:/Users/<username>/.cache/puppeteer. I located chrome.exe there and copied the full path to it.
- Edited markdown-extended settings and entered that path into 'Puppeteer executable'.

Now I can export my md files to pdf with version 1.1.4.

**Comment by dominotec** [comment]
# Steps to Fix Markdown Extended Version 1.1.3 to Version 1.1.4 with Windows 10 and Windows 11

- Windows command line: Open the **Windows command line** (press Win+R) **as Administrator**.

- Windows command line: Check if Node.js/NPM is installed by running **node -v** and **npm -v**.

``
C:\Windows\System32>node -v
Der Befehl "node" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
``
``
C:\Windows\System32>npm -v
Der Befehl "npm" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
``

- Windows command line: If you encounter errors when running **node -v** and **npm -v**, download the latest Node.js MSI package from https://nodejs.org/en.

![2024-12-01-01](https://github.com/user-attachments/assets/6748e2d7-7c7e-497c-aed7-3fa5d8af422e)

- Node.js: Run the basic installation MSI package **node-v22.11.0-x64.msi** from your Downloads directory.

![2024-12-01-02](https://github.com/user-attachments/assets/d031191b-a684-400d-9717-a96dd3877c54)

- Windows command line: Check if Node.js/NPM is installed by running **node -v** and **npm -v**. Example output: node -v = v22.11.0, npm -v = 10.9.0.
 
![2024-12-01-03](https://github.com/user-attachments/assets/dce762f3-4797-42e5-a3eb-e8853a2f31fa)

- Windows command line: Check if Puppeteer is installed by running **npm list puppeteer**. Output: puppeteer@23.9.0. Additional commands: **npm uninstall puppeteer**, **npm install puppeteer**, **npm cache clean --force**.

![2024-12-01-04](https://github.com/user-attachments/assets/937d8c52-fd52-4567-9bb7-557b3a2a469f)

- Check Puppeteer directory/chrome.exe: Verify the directory at **C:\Users\\"your windows user account"\\.cache\puppeteer\chrome\win64-131.0.6778.85\chrome-win64** (Check: chrome.exe).

![2024-12-01-06](https://github.com/user-attachments/assets/c8a32fd2-a977-40fa-a56d-febaab301f4b)

- vsCode: In the **Markdown Extended extension settings** (@ext:jebbs.markdown-extended), set the correct path to Puppeteer chrome.exe (also modified in User/Workspace). <br><br>Example: **C:\Users\\"your windows user account"\\.cache\puppeteer\chrome\win64-131.0.6778.85\chrome-win64\chrome.exe**

![2024-12-01-05](https://github.com/user-attachments/assets/e4ca430f-8cc2-407e-a00b-4754dc833a4d)

- vsCode: Update Markdown Extended extension from version 1.1.3 to 1.1.4.

![2024-12-01-07](https://github.com/user-attachments/assets/2c764dff-3659-47dd-86a5-095c222f510a)

- vsCode: **Test Markdown Extended** with **Export to File**. **Output: 1 file(s) exported in 14.329 seconds: c:\temp\markdown\test.pdf** - **without errors** Could not find Chromium (rev. 1108766)...

The Markdown Extended extension Version 1.1.4, Export to File is up and running with vsCode

Version: 1.95.3 (user setup)
Chromium: 128.0.6613.186
Node.js: 20.18.0

**Comment by piridium** [comment]
Thank you @Manu-Caminos and @dominotec, your contributions have helped me to fix the problem on macOS as well.
I didn't even have to install puppeteer using npm, I could just point the configuration to the already installed Chrome browser. I had already tried that several times, but I must have put the path in quotation marks which did not seem to work.

If I change the path to the puppeteer executable to `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome` as in the example given - but without `'`, then the export works again.

How to get there:
1. Press shift-cmd-P and type "open user settings"
1. Navigate to "Extensions" and "Markdown Extended"
1. Find the configuration for "Puppeteer Executable" and paste the path to your chrome executable.

**Comment by michael72** [comment]
OK - so puppeteer was added (completely) to the setup before. It was removed with this [commit](https://github.com/qjebbs/vscode-markdown-extended/commit/0146ea37480f5954af9b5b31bee884b824f899e5).
However afterwards the export didn't work any more.
I am not sure: @qjebbs are you still working on this plugin at all?
