### ISSUE TITLE
i get `command 'markdownExtended.export' not found`

### ISSUE THREAD

**Issue by qintang** [qjebbs/vscode-markdown-extended#2]
when i want export to html. then opps~~~

**Comment by qjebbs** [comment]
please open the development tool and copy the console output for me.

**Comment by amoosbr** [comment]
Hi,
i have the same issue. Below the output from the development tools console.
I have the extension 'Markdown Preview Github Styling' installed. But I don't know, if I would need to enable 'Markdown Preview Github Styling' somewhere or if the extension is enabled by default.
From my knowledge, I don't have another preview style extension installed.

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Activating extension `jebbs.markdown-extended` failed:  Cannot read property 'markdown.previewStyles' of undefined
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'markdown.previewStyles' of undefined
	at String.vscode.extensions.all.map (/home/user/.vscode/extensions/jebbs.markdown-extended-0.1.3/out/src/common/styles.js:10:48)
	at Array.map (native)
	at readStyles (/home/user/.vscode/extensions/jebbs.markdown-extended-0.1.3/out/src/common/styles.js:9:27)
	at Object.<anonymous> (/home/user/.vscode/extensions/jebbs.markdown-extended-0.1.3/out/src/common/styles.js:6:24)
	at Object.<anonymous> (/home/user/.vscode/extensions/jebbs.markdown-extended-0.1.3/out/src/common/styles.js:23:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4054 Activating extension `jebbs.markdown-extended` failed: Cannot read property 'markdown.previewStyles' of undefined.
t._logMessageInConsole @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4054
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2742 command 'markdownExtended.copy.withStyle' not found
```

**Comment by amoosbr** [comment]
Thanks for the quick fix. HTML export is working great now.

**Comment by qjebbs** [comment]
Good to hear. Thanks for feedback. @qintang's issue should also be fixed, closing this issue now..
