### ISSUE TITLE
None of the Markdown-It Features work

### ISSUE THREAD

**Issue by altimmons** [qjebbs/vscode-markdown-extended#25]
In fact, they crash most the preview apps Ive used.

Admonition works- which is the primary thing I care about.  But I am trying to minimize extensions,

I dont see any requirements or packages I need.  Perhaps thats an issue,

Otherwise, maybe we could get an admonition only extension,

Or I will work on my own extension picking each feature I like.

**Comment by altimmons** [comment]
Got it  

Cannot read property 'document' of undefined
TypeError: Cannot read property 'document' of undefined
    at Object.toggleFormat (C:\Users\s163837\.vscode\extensions\jebbs.markdown-extended-1.0.2\out\src\services\helpers\toggleFormat.js:7:27)
    at toggle (C:\Users\s163837\.vscode\extensions\jebbs.markdown-extended-1.0.2\out\src\commands\toggleFormats.js:109:20)
    at C:\Users\s163837\.vscode\extensions\jebbs.markdown-extended-1.0.2\out\src\commands\commands.js:18:26
    at e._executeContributedCommand (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:160)
    at e.$executeContributedCommand (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:648)
    at t._doInvokeHandler (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:757)
    at t._invokeHandler (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:423)
    at t._receiveRequest (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:15)
    at t._receiveOneMessage (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:606:957)
    at c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
    at c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
    at e.fire (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
    at a (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
    at Socket._socketDataListener (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

**Comment by altimmons** [comment]
It worked until the Footnote feature, in the extension explanation page and then no further features,  Failure to render, or crash,
