### ISSUE TITLE
Markdown It Features

### ISSUE THREAD

**Issue by altimmons** [qjebbs/vscode-markdown-extended#26]
I accidentally closed the last one.  I dont know what Im doing.  Sorry.  

None of the features that start with Markdown it for me work- In fact, they crash most the preview apps Ive used. Admonition works- which is the primary thing I care about. But I am trying to minimize extensions.  It worked until the Footnote feature, in the extension explanation page and then no further features, Failure to render, or crash, You'd think at least it would just render the text.

I dont see any requirements or packages I need. Perhaps thats an issue,

Otherwise, maybe we could get an admonition only extension,

The closest thing I got to an error was this: But it was just once.  Usually it was just a blank Preview.  Or a preview up until I used the bit of Markup.

Cannot read property 'document' of undefined
TypeError: Cannot read property 'document' of undefined
at Object.toggleFormat (C:\Users\s163837.vscode\extensions\jebbs.markdown-extended-1.0.2\out\src\services\helpers\toggleFormat.js:7:27)
at toggle (C:\Users\s163837.vscode\extensions\jebbs.markdown-extended-1.0.2\out\src\commands\toggleFormats.js:109:20)
at C:\Users\s163837.vscode\extensions\jebbs.markdown-extended-1.0.2\out\src\commands\commands.js:18:26
at e._executeContributedCommand (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:160)
at e.$executeContributedCommand (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:648)
at t._doInvokeHandler (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:757)
at t._invokeHandler (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:423)
at t._receiveRequest (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:15)
at t._receiveOneMessage (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:606:957)
at c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
at c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
at e.fire (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
at a (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
at Socket._socketDataListener (c:\Users\s163837\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at Pipe.onread (net.js:594:20)

**Comment by qjebbs** [comment]
This error log is about the helper(when no editor's open, I'll fix it), not about the features. 

Every feature works good here, I would say, try disable any other markdown extensions, since there are potentially conflicts.

**Comment by altimmons** [comment]
Yea, I will have to go through them bit by bit.

Its complicated that I am running on 4 different machines.  I am working on
standarizing things as well.

Andy
