### ISSUE TITLE
Timeout when exporting to pdf

### ISSUE THREAD

**Issue by Trivernis** [qjebbs/vscode-markdown-extended#44]
## Stats

OS: Windows 10 VM 64bit

VS-Code-Version: 1.33.1

Extension Version: 1.0.8

## Summary

The pdf-export throws an error that it exceeded the timeout of 30 seconds. The export to HTML works fine. The file I want to export is 500 lines long. It would be great if there was a way to modify the timeout for the exports via settings.

## Stacktrace

```
Navigation Timeout Exceeded: 30000ms exceeded
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
	at _createTimeoutPromise.Promise.then (C:\Users\dev\.vscode\extensions\jebbs.markdown-extended-1.0.8\node_modules\puppeteer\lib\FrameManager.js:1230:21)
  -- ASYNC --
	at Frame.<anonymous> (C:\Users\dev\.vscode\extensions\jebbs.markdown-extended-1.0.8\node_modules\puppeteer\lib\helper.js:144:27)
	at Page.goto (C:\Users\dev\.vscode\extensions\jebbs.markdown-extended-1.0.8\node_modules\puppeteer\lib\Page.js:579:49)
	at Page.<anonymous> (C:\Users\dev\.vscode\extensions\jebbs.markdown-extended-1.0.8\node_modules\puppeteer\lib\helper.js:145:23)
	at PuppeteerExporter.<anonymous> (C:\Users\dev\.vscode\extensions\jebbs.markdown-extended-1.0.8\out\src\services\exporter\puppeteer.js:62:24)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\dev\.vscode\extensions\jebbs.markdown-extended-1.0.8\out\src\services\exporter\puppeteer.js:4:58)
```

**Comment by aefreedman** [comment]
I am also having timeout issues with PDF exporter, especially when including a "large" png (something too big for the page) or multiple small pngs (small enough for page).

Exporting to HTML and then printing the HTML page as PDF from the browser works fine.

**Comment by qjebbs** [comment]
Seems that later Chromium doesn't support `goto(`data:text/html,...)`, I've update dependencies, please update.
