### ISSUE TITLE
Fail to render link with attrs

### ISSUE THREAD

**Issue by zlsun** [qjebbs/vscode-markdown-extended#58]
When render following code in vscode
```md
# Test
[Google](http://google.com){target="blank"}
```
Exception throw and preview tab is empty.
```
TypeError: Cannot read property 'attrPush' of undefined
	at Object.exports.addAttrs (c:\Users\name\.vscode\extensions\jebbs.markdown-extended-1.0.11\node_modules\markdown-it-attrs\utils.js:104:13)
	at Object.transform (c:\Users\name\.vscode\extensions\jebbs.markdown-extended-1.0.11\node_modules\markdown-it-attrs\patterns.js:122:13)
	at Array.curlyAttrs (c:\Users\name\.vscode\extensions\jebbs.markdown-extended-1.0.11\node_modules\markdown-it-attrs\index.js:20:19)
	at a.process (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:123314)
	at h.parse (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:88828)
	at t.MarkdownEngine.tokenizeString (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:83738)
	at t.MarkdownEngine.tokenizeDocument (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:83639)
	at t.MarkdownEngine.render (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:83913)
```

I search with the exception above and find this similar issue
https://github.com/arve0/markdown-it-attrs/issues/90

Extension version: 1.0.11
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763

**Comment by qjebbs** [comment]
should've fixed with latest release
